# Generated by Django 3.2.8 on 2021-10-16 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True, verbose_name='Name')),
                ('avatar', models.ImageField(default='users/avatar/default.jpg', upload_to='users/avatar/', verbose_name='Profile photo')),
                ('phone', models.CharField(max_length=50, verbose_name='Phone number')),
                ('card_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Card number')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='When contact is created')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='When contact is updated')),
            ],
            options={
                'db_table': 'contacts',
            },
        ),
    ]
