# Generated by Django 3.2.8 on 2021-10-14 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, verbose_name='Username')),
                ('phone', models.CharField(max_length=50, verbose_name='Phone number')),
                ('address', models.CharField(blank=True, max_length=250, null=True, verbose_name='Address')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Any comment about contact')),
                ('card_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Card number')),
                ('debt_type', models.CharField(choices=[('lent', 'Lend'), ('borrowed', 'Borrow'), ('paid', 'Paid')], max_length=50, verbose_name='Type of debt')),
                ('debt_started_on', models.DateTimeField(verbose_name='Date when debt was given/taken')),
                ('debt_end_on', models.DateTimeField(verbose_name='Date when debt should be returned')),
                ('debt_amount', models.IntegerField(verbose_name='Debt amount')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('debt_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contacts.currency')),
            ],
            options={
                'db_table': 'contacts',
            },
        ),
    ]
