# Generated by Django 3.2.8 on 2021-10-23 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contact_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='avatar',
            field=models.ImageField(default='contacts/avatar/default.jpg', upload_to='contacts/avatar/', verbose_name='Profile photo'),
        ),
    ]
