# Generated by Django 3.2.8 on 2021-10-16 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_auto_20211014_2259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='address',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='debt_amount',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='debt_currency',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='debt_end_on',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='debt_started_on',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='debt_type',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='username',
        ),
        migrations.AddField(
            model_name='contact',
            name='avatar',
            field=models.ImageField(default='users/avatar/default.jpg', upload_to='users/avatar/', verbose_name='Profile photo'),
        ),
        migrations.AddField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=150, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='When contact is created'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, verbose_name='When contact is updated'),
        ),
        migrations.DeleteModel(
            name='Currency',
        ),
    ]
