# Generated by Django 3.2.8 on 2021-10-23 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='debt',
            old_name='updated_on',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='phone_number',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='debt',
            name='type',
        ),
        migrations.AddField(
            model_name='debt',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='debt',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Is returned'),
        ),
        migrations.AddField(
            model_name='debt',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Is returned at'),
        ),
        migrations.AddField(
            model_name='debt',
            name='paid_at_auto',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='debt',
            name='type_debt',
            field=models.CharField(choices=[(1, 'Lend'), (2, 'Borrow')], default=2, max_length=50, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='debt',
            name='end_on',
            field=models.DateTimeField(blank=True, verbose_name='Date when it has to be returned'),
        ),
        migrations.AlterField(
            model_name='debt',
            name='started_on',
            field=models.DateTimeField(blank=True, verbose_name='Date when it was given/taken'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sms_code',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='SMS code'),
        ),
    ]
