# Generated by Django 3.2.8 on 2021-10-23 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211023_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt',
            name='type_debt',
            field=models.IntegerField(choices=[(1, 'Lend'), (2, 'Borrow')], default=2, max_length=50, verbose_name='Type'),
        ),
    ]
