# Generated by Django 3.2.8 on 2021-10-23 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_debt_type_debt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt',
            name='type_debt',
            field=models.IntegerField(choices=[(1, 'Lend'), (2, 'Borrow')], default=2, verbose_name='Type'),
        ),
    ]
