# Generated by Django 3.2.8 on 2021-10-23 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_debt_type_debt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt',
            name='end_on',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date when it has to be returned'),
        ),
        migrations.AlterField(
            model_name='debt',
            name='paid',
            field=models.BooleanField(blank=True, null=True, verbose_name='Is returned'),
        ),
        migrations.AlterField(
            model_name='debt',
            name='started_on',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date when it was given/taken'),
        ),
    ]
