# Generated by Django 3.2.8 on 2021-10-25 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_debt_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Is returned'),
        ),
    ]
